### ISSUE TITLE
Unable to return the objective as a linear expression after reading a .mps file

### ISSUE THREAD

**Issue by sgreysond** [coin-or/python-mip#8]
I think I've found a bug in version 1.3.13 of the PyPI MIP package. I'm reading a MIP from a .mps file and trying to see what the objective function is. But, rather than returning the linear expression I'm expecting, I'm getting an error message. I'm running this code in Python 3.7:

m = Model(sense=MINIMIZE, solver_name="cbc")
m.read('q_consol_4.mps')
m.objective

And I'm getting back:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-d351ec8244c2>", line 1, in <module>
    m.objective
  File "/usr/local/lib/python3.7/site-packages/mip/model.py", line 933, in objective
    return self.solver.get_objective()
  File "/usr/local/lib/python3.7/site-packages/mip/cbc.py", line 409, in get_objective
    return xsum(obj[j]*self.vars[j] for j in range(self.num_cols)
TypeError: 'method' object cannot be interpreted as an integer

If I chase the error into the get_objective function, I find that self.vars doesn't seem to exist; if, in a debugging environment, I reach line 409 of cbc.py and enter

self.vars[0]

I get

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-64b911e8f0f0>", line 1, in <module>
    self.vars[0]
AttributeError: 'SolverCbc' object has no attribute 'vars'

Interestingly, the optimize() method seems to work just fine. So the objective-function data should be available, but I just can't return the linear expression with m.objective.

Is there a quick fix for this?

**Comment by h-g-s** [comment]
tentative fix on 1.3.14,  could you try ?

**Comment by sgreysond** [comment]
I can see what you did (i.e., adding the parentheses to num_cols on line 409). But I now get 

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-d351ec8244c2>", line 1, in <module>
    m.objective
  File "/usr/local/lib/python3.7/site-packages/mip/model.py", line 933, in objective
    return self.solver.get_objective()
  File "/usr/local/lib/python3.7/site-packages/mip/cbc.py", line 409, in get_objective
    return xsum(obj[j]*self.vars[j] for j in range(self.num_cols())
  File "/usr/local/lib/python3.7/site-packages/mip/model.py", line 1952, in xsum
    for term in terms:
  File "/usr/local/lib/python3.7/site-packages/mip/cbc.py", line 410, in <genexpr>
    if abs(obj[j]) >= 1e-15)
AttributeError: 'SolverCbc' object has no attribute 'vars'

**Comment by h-g-s** [comment]
it should be   self.model.vars      could you try to modify in your version and see if it works ?

**Comment by sgreysond** [comment]
That does the trick!

**Comment by h-g-s** [comment]
good. I released 1.3.15 with the fix, please check my update if it works ok.

**Comment by sgreysond** [comment]
Yes, the update does seem to work. Really appreciate the quick fix, and the package as a whole.

**Comment by h-g-s** [comment]
you're welcome!
